
services:
  snowflake:
    epoch: 1704067200000
    worker-id-bit: 10
    sequence-id-bit: 12
    worker-id: ${workerid:1}


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
